version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: k6G1tgJLM9hMXvwR
      MYSQL_DATABASE: zakazio_db
    ports:
      - "3306:3306"

  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql-developmentgit
    environment:
      API_URL: http://localhost:8080/api/v1
      CRM_URL: http://localhost
      CLOUD_PAYMENT_PUBLIC: pk_8507dee1d9c8b1519a3f5b5b3d872
      CLOUD_PAYMENT_PRIVATE: 0e9f48b377588f22f628825b7f1e42f0