version: '3.4'

services:

  mysql-development:
    image: mysql:8.0.17
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: k6G1tgJLM9hMXvwR
      MYSQL_DATABASE: zakazio_db
    ports:
      - "3307:3306"

  api:
    build: api
    container_name: api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql-development
    environment:
      API_URL: https://api.zakazy.online/api/v1
      CRM_URL: https://crm.zakazy.online
      CLOUD_PAYMENT_PUBLIC: pk_81a3630bdf32633b8b1e1626dea96
      CLOUD_PAYMENT_PRIVATE: 4aef85996813fe9d42b5a9585ce9eda5
      EXTRA_FILE_URL: https://file.zakazy.online
    volumes:
      - /home/storage:/home/storage

  socket:
    build: socket
    container_name: socket
    ports:
      - 8181:8181
    environment:
      CRM_URL: https://crm.zakazy.online


  open:
    build: open
    container_name: open
    ports:
      - 3737:3737

  nginx:
    container_name: nginx
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: owner@company.com
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./etc/var/www/data:/var/www/data
      - ./crm/build/web:/site/crm
      - ./sdk/build:/site/sdk
      - /home/storage:/home/storage
